damping_kd:
  - 10
  - 10
  - 10
  - 10
  - 4
  - 4

  - 10
  - 10
  - 10
  - 10
  - 4
  - 4

  - 6
  - 6
  - 6

  - 2
  - 2

  - 10
  - 10
  - 5
  - 5
  - 2
  - 2
  - 2

  - 10
  - 10
  - 5
  - 5
  - 2
  - 2
  - 2
